name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - 'releases/*'

permissions: {}

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-test
        run: npm run test

  test-action:
    name: Test action
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v6

      - name: Run action No env
        id: otel-context-no-env
        uses: ./
        with:
          output-env: false

      - name: Assert TRACEPARENT env is empty
        run: test -z "${TRACEPARENT}"

      - name: Assert traceparent is not empty
        run: test -n "${{ steps.otel-context-no-env.outputs.traceparent }}"

      - name: Run action
        id: otel-context
        uses: ./

      - name: Assert traceparent is not empty
        run: test -n "${{ steps.otel-context.outputs.traceparent }}"

      - name: Assert TRACEPARENT env is not empty
        run: test -n "${TRACEPARENT}"

  test-e2e:
    name: Test action e2e
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v6

      - name: Run action
        id: otel-context
        uses: ./

      - name: install otel-cli
        run: go install github.com/equinix-labs/otel-cli@latest

      - name: run otel-cli
        run: |
          $(go env GOPATH)/bin/otel-cli exec \
            --service my-service \
            --name "curl google" \
            curl https://google.com
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: ${{ secrets.OTEL_ENDPOINT }}
          OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_HEADER }}
          TRACEPARENT: ${{ steps.otel-context.outputs.traceparent }}
